configure: check for pr
Configuration logging is padded through pr. Make sure it's
present.

Change-Id: I451217882a329c2bfb8942ac86ac624a7feef670

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -164,6 +164,11 @@ if ! perl --version >/dev/null; then
     die "Perl is required to build"
 fi
 
+if ! pr --version >/dev/null; then
+    # pr is used to output the configuration log.
+    die "pr is required to build"
+fi
+
 # check installed doxygen version
 doxy_version=$(doxygen --version 2>/dev/null)
 doxy_major=${doxy_version%%.*}
